name: Metrics

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Stats + Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          config_theme: dark
          config_padding: 6%, 10%
          config_display: large

      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_theme: dark

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_languages_limit: 6
          config_theme: dark

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          config_theme: dark

      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: push, pr, issue, release
          config_theme: dark